/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareaarreglada;

import java.io.IOException;
import java.sql.CallableStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author dashs
 */
public class Ag_Ani extends javax.swing.JFrame {

    /**
     * Creates new form Ag_Ani
     */
    public Ag_Ani() {
        initComponents();
        setLocationRelativeTo(null); // Centrar en la pantalla
        setResizable(false); // Desactivar la posibilidad de redimensionar
        OcultoAnimal.setVisible(false);
        OcultoGrupo.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_grupo = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Imagen = new javax.swing.JLabel();
        anit = new javax.swing.JPanel();
        anis = new javax.swing.JLabel();
        anitt = new javax.swing.JLabel();
        asig = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        CB2 = new javax.swing.JComboBox<>();
        CB3 = new javax.swing.JComboBox<>();
        CB4 = new javax.swing.JComboBox<>();
        CB1 = new javax.swing.JSlider();
        valor = new javax.swing.JLabel();
        decimal = new javax.swing.JSlider();
        asdecimal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        OcultoAnimal = new javax.swing.JLabel();
        OcultoGrupo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Animal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 14))); // NOI18N

        Tabla_grupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla_grupo);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Animal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 2, 12))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
        );

        anit.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        anis.setText("Animal seleccionado");

        anitt.setText("Tipo");

        asig.setText("Grupo");

        javax.swing.GroupLayout anitLayout = new javax.swing.GroupLayout(anit);
        anit.setLayout(anitLayout);
        anitLayout.setHorizontalGroup(
            anitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anitLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(anitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(asig)
                    .addComponent(anitt)
                    .addComponent(anis))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        anitLayout.setVerticalGroup(
            anitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(anitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(anis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(anitt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(asig)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jButton1.setText("Generar Animal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Caracteristicas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CB2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Color", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.add(CB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 127, 111, 49));

        CB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB3ActionPerformed(evt);
            }
        });
        jPanel4.add(CB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 102, -1));

        CB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB4ActionPerformed(evt);
            }
        });
        jPanel4.add(CB4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 102, -1));

        CB1.setMajorTickSpacing(20);
        CB1.setToolTipText("");
        CB1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                CB1StateChanged(evt);
            }
        });
        CB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CB1MouseClicked(evt);
            }
        });
        jPanel4.add(CB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 50, 227, 22));

        valor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        valor.setText("0");
        jPanel4.add(valor, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 27, 43, 17));

        decimal.setMaximum(999);
        decimal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                decimalStateChanged(evt);
            }
        });
        jPanel4.add(decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 101, 227, -1));

        asdecimal.setText("0");
        jPanel4.add(asdecimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 40, -1));

        jLabel1.setText("Kg");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        jLabel2.setText("g");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, -1));

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Aceptar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(anit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(410, 410, 410)
                                .addComponent(OcultoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(OcultoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(anit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(OcultoGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(OcultoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        CB4.setVisible(false);//Se desactiva el boton CB4 de la pantalla, y solo se activa cuando se piden 5 variables
        CAnimal Az = new CAnimal();//se crea instancia Az que llama a CAnimal


        try {
            Az.AnimalAzar(Tabla_grupo,anis, anitt, asig,Imagen,CB1,CB2,CB3,CB4,OcultoAnimal,OcultoGrupo,decimal);//se llama a la funcion Animal al Azar con su instancia Az en CAnimales 
        } catch (IOException ex) {
            Logger.getLogger(Ag_Ani.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Esta es la accion del boton volver hacemos la nueva instancia del Menu y luego le decimos que se haga visible para acto despues usar this.dispose() para cerrar la ventana actual.
        Menu volver = new Menu();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CB1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_CB1StateChanged
        int value = CB1.getValue();//se obtiene el valor de el peso en kg en tiempo real, 
        valor.setText(Integer.toString(value));//obtiene el valor del peso y lo muestra en pantalla a travez de un label
    }//GEN-LAST:event_CB1StateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        double Pesogen  = CB1.getValue();//se obtienen el valor del peso en kg
        double  PesoDecmal = decimal.getValue();//se obtiene el valor del peso en g
        double PesoAnimal= Pesogen+(PesoDecmal/1000);//calculo para obtener el peso comleto, es decir la suma de lo decimal y lo entero
        String ColorAnimal = CB2.getSelectedItem().toString();//se obtiene el color del combobox
        String Carac_especial1 = CB3.getSelectedItem().toString();//se obtiene la caracteristica especial 
        Boolean Carac_especial2 = (Boolean) CB4.getSelectedItem();//se obtiene la caracteristica especial 2
        String NombreAnimal = OcultoAnimal.getText().toString();//Obtiene un valor oculto dentro del programa el cual no se muetra por pantalla pero nos permite determinar el nombre y el grupo del animal
        String GrupoAnimal = OcultoGrupo.getText().toString();//Obtiene un valor oculto dentro del programa el cual no se muetra por pantalla pero nos permite determinar el nombre y el grupo del animal


        if(GrupoAnimal.equals("Mamíferos")|| GrupoAnimal.equals("Aves") ||GrupoAnimal.equals("Anfibios")|| GrupoAnimal.equals("Reptiles") ||GrupoAnimal.equals("Moluscos")|| GrupoAnimal.equals("Equinodermos")||GrupoAnimal.equals("Celentéreos")){
            CAnimal INS4 = new CAnimal();//si el grupo animal tiene 4 caracteristicas se ingresa a la funcion insertar 4 caracteristicas dentro de CAnimales 
            INS4.InsertarCarac4(NombreAnimal, PesoAnimal, ColorAnimal, Carac_especial1, GrupoAnimal,Tabla_grupo);
        }else if (GrupoAnimal.equals("Poríferos")){
            CAnimal INS3 = new CAnimal();//si el grupo animal tiene 3 caracteristicas se ingresa a la funcion insertar 3 caracteristicas dentro de CAnimales 
            INS3.InsertarCarac3(NombreAnimal, PesoAnimal, ColorAnimal,GrupoAnimal,Tabla_grupo);
        }else if (GrupoAnimal.equals("Peces")|| GrupoAnimal.equals("Artrópodos")){
            CAnimal INS5 = new CAnimal();//si el grupo animal tiene 5 caracteristicas se ingresa a la funcion insertar 5 caracteristicas dentro de CAnimales 
            INS5.InsertarCarac5(NombreAnimal, PesoAnimal, ColorAnimal, Carac_especial1, Carac_especial2,GrupoAnimal,Tabla_grupo);
        }else{
            JOptionPane.showMessageDialog(null, "No se ingreso ningun animal");
        }

        CB4.setVisible(false);//Se desactiva el boton CB4 de la pantalla, y solo se activa cuando se piden 5 variables
        
        
        
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CB1MouseClicked
        
    }//GEN-LAST:event_CB1MouseClicked

    private void CB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB4ActionPerformed

    private void decimalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_decimalStateChanged
        int value = decimal.getValue();//se obtiene el valor de el peso en g  en tiempo real
        asdecimal.setText(Integer.toString(value));//obtiene el valor del peso y lo muestra en pantalla a travez de un label
    }//GEN-LAST:event_decimalStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ag_Ani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ag_Ani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ag_Ani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ag_Ani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ag_Ani().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSlider CB1;
    private javax.swing.JComboBox<String> CB2;
    private javax.swing.JComboBox<String> CB3;
    private javax.swing.JComboBox<String> CB4;
    private javax.swing.JLabel Imagen;
    private javax.swing.JLabel OcultoAnimal;
    private javax.swing.JLabel OcultoGrupo;
    private javax.swing.JTable Tabla_grupo;
    private javax.swing.JLabel anis;
    private javax.swing.JPanel anit;
    private javax.swing.JLabel anitt;
    private javax.swing.JLabel asdecimal;
    private javax.swing.JLabel asig;
    private javax.swing.JSlider decimal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
