/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareaarreglada;

import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author dashs
 */
public class PJ_TipoGrupo extends javax.swing.JFrame {

    /**
     * Creates new form PJ_TipoGrupo
     */
    public PJ_TipoGrupo() {
        initComponents();
        Imposible1.setEditable(false);//Hacemos que al usuario le sea imposible editar este Imposible1
        Imposible2.setEditable(false);//Hacemos que al usuario le sea imposible editar este Imposible2
        setLocationRelativeTo(null); // Centrar en la pantalla
        setResizable(false); // Desactivar la posibilidad de redimensionar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Imposible1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Imposible2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Seleccione para hacer la busqueda");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Vertebrado");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Invertebrado");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Porcentaje Tipo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        Imposible1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Imposible1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Imposible1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imposible1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Porcentaje Grupo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(Imposible2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imposible2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jButton2.setText("Volver");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(101, 101, 101)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jButton1)
                .addGap(163, 163, 163)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addComponent(jButton2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Imposible1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Imposible1ActionPerformed
        
    }//GEN-LAST:event_Imposible1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        //Aqui le vamos a dar valores al combobox cuando se seleccione JRadioButton1 "Vertebrados"
        String[] elementosOpcion1 = {"Mamíferos", "Aves", "Peces","Anfibios","Reptiles"};
        jComboBox1.setModel(new DefaultComboBoxModel<>(elementosOpcion1));
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        //Aqui le vamos a dar valores al combobox cuando se seleccione JRadioButton2 "Invertebrados"
        String[] elementosOpcion2 = {"Artrópodos", "Moluscos","Equinodermos","Gusanos","Poríferos","Celentéreos"};
        jComboBox1.setModel(new DefaultComboBoxModel<>(elementosOpcion2));
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        float sumaV;
        float sumaI;
        float sumaTotal;
        float cantidadGrupo;
        float porcentaje = 0;
        float porcentajeTipoVertebrado;
        float porcentajeTipoInvertebrado;
        String botonSeleccionado;
        CAnimal c = new CAnimal();        
        sumaV = c.obtenerCantidadFilas("mamíferos")+c.obtenerCantidadFilas("aves")+c.obtenerCantidadFilas("peces")+c.obtenerCantidadFilas("anfibios")+c.obtenerCantidadFilas("reptiles");
        sumaI = c.obtenerCantidadFilas("artrópodos")+c.obtenerCantidadFilas("moluscos")+c.obtenerCantidadFilas("equinodermos")+c.obtenerCantidadFilas("gusanos")+c.obtenerCantidadFilas("poríferos")+c.obtenerCantidadFilas("celentéreos");
        //System.out.println("Mira la suma vertebrados : "+sumaV );
        //System.out.println("Mira la suma invertebrados : "+sumaI );
        sumaTotal = sumaI + sumaV;
        //System.out.println("Mira la suma total : "+sumaTotal );
        porcentajeTipoVertebrado = sumaV * 100/sumaTotal;//Sacamos
        //System.out.println("Mira el porcentaje vertebrado : "+porcentajeTipoVertebrado );
        porcentajeTipoInvertebrado = sumaI * 100/sumaTotal;
        //System.out.println("Mira el porcentaje invertebrado : "+porcentajeTipoInvertebrado );
        //Rescatamos el item seleccionado en el JComboBox1 
        String itemSeleccionado = jComboBox1.getSelectedItem().toString();
        //Preguntamos si el jRadioButton1 fue seleccionado de ser asi entramos aqui y en el caso contrario entramos al else
        if(jRadioButton1.isSelected()){
            botonSeleccionado = "Vertebrados";
            if(itemSeleccionado.equalsIgnoreCase("Mamíferos")) {//Si el item seleccionado es Mamíferos entramos aquí 
                cantidadGrupo = c.obtenerCantidadFilas("mamíferos");//Mandamos "mamíferos" a obtenerCantidadFilas para saber la cantidad de filas de la tabla mamíferos
                porcentaje = cantidadGrupo * 100 / sumaTotal;//Sacamos el porcentaje que sera el total de filas en la tabla mamíferos por 100 partido en la cantidad total de animales en el zoologico
            } else if(itemSeleccionado.equalsIgnoreCase("Aves")) {
                cantidadGrupo = c.obtenerCantidadFilas("aves");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Peces")) {
                cantidadGrupo = c.obtenerCantidadFilas("peces");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Anfibios")) {
                cantidadGrupo = c.obtenerCantidadFilas("anfibios");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Reptiles")) {
                cantidadGrupo = c.obtenerCantidadFilas("reptiles");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            }
            Imposible1.setText(porcentajeTipoVertebrado + "%");//Al JTextField Imposible1 le pasamos el porcentaje del tipo Vertebrados (En este caso) 
            Imposible2.setText(porcentaje + "%");//Al JTextField Imposible2 le pasamos el porcentaje del grupo
        } 
        else if(jRadioButton2.isSelected()) {
            botonSeleccionado = "Invertebrados";
            if(itemSeleccionado.equalsIgnoreCase("Artrópodos")) {
                cantidadGrupo = c.obtenerCantidadFilas("artrópodos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Moluscos")) {
                cantidadGrupo = c.obtenerCantidadFilas("moluscos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Equinodermos")) {
                cantidadGrupo = c.obtenerCantidadFilas("equinodermos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Gusanos")) {
                cantidadGrupo = c.obtenerCantidadFilas("gusanos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Poríferos")) {
                cantidadGrupo = c.obtenerCantidadFilas("poríferos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            } else if(itemSeleccionado.equalsIgnoreCase("Celentéreos")) {
                cantidadGrupo = c.obtenerCantidadFilas("celentéreos");
                porcentaje = cantidadGrupo * 100 / sumaTotal;
            }
            Imposible1.setText(porcentajeTipoInvertebrado + "%");//Al JTextField Imposible1 le pasamos el porcentaje del tipo Invertebrados (En este caso) 
            Imposible2.setText(porcentaje + "%");//Al JTextField Imposible2 le pasamos el porcentaje del grupo
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Esta es la accion del boton volver hacemos la nueva instancia del Menu y luego le decimos que se haga visible para acto despues usar this.dispose() para cerrar la ventana actual.
        Menu volver = new Menu();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PJ_TipoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PJ_TipoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PJ_TipoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PJ_TipoGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PJ_TipoGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Imposible1;
    private javax.swing.JTextField Imposible2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
}
