/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tareaarreglada;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathi
 */
public class Prom_TOG extends javax.swing.JFrame {

    /**
     * Creates new form Prom_TOG
     */
    public Prom_TOG() {
        initComponents();
        jTextField1.setEnabled(false);
        setLocationRelativeTo(null); // Centrar en la pantalla
        setResizable(false); // Desactivar la posibilidad de redimensionar
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        AquiReciboElTipoOGrupo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTextArea1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese el tipo o grupo del cual quiere saber su promedio Peso:");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(AquiReciboElTipoOGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(AquiReciboElTipoOGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jButton3.setText("Volver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Peso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 0, 0))); // NOI18N

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CAnimal an = new CAnimal();
        double peso = 0.0;
        String tipo =" ";
        String recibido = AquiReciboElTipoOGrupo.getText();
        List<String> ListaBlanca = Arrays.asList("Invertebrados","Vertebrados","Mamíferos", "Anfibios", "Artrópodos", "Aves", "Celentéreos", "Equinodermos", "Gusanos", "Moluscos", "Peces", "Poríferos", "Reptiles");
        if (!ListaBlanca.contains(recibido)) {
            JOptionPane.showMessageDialog(null, "El tipo o grupo de animales ingresado no es válido.", "Error", JOptionPane.ERROR_MESSAGE);
        }else {
            Conexion co = new Conexion();
            if(recibido.equals("Vertebrados")){
                try {
                    tipo = "Vertebrado";
                    //Al ser el promedio peso de vertebrados sumamos el promedio de peso de todos los grupos de vertebrados y los dividimos en su cantidad para obtener el peso promedio de vertebrados
                    peso = (an.CalcularPesoProm(1) + an.CalcularPesoProm(2) + an.CalcularPesoProm(3)+an.CalcularPesoProm(4)+an.CalcularPesoProm(5))/5;
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Invertebrados")){
                try {
                    tipo = "Invertebrados";
                    //Al ser el promedio peso de vertebrados sumamos el promedio de peso de todos los grupos de invertebrados y los dividimos en su cantidad para obtener el peso promedio de invertebrados
                    peso = (an.CalcularPesoProm(6) + an.CalcularPesoProm(7) + an.CalcularPesoProm(8)+an.CalcularPesoProm(9)+an.CalcularPesoProm(10)+an.CalcularPesoProm(11))/6;
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Mamíferos")){
                try {
                    tipo = "Mamíferos";
                    peso = an.CalcularPesoProm(1);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Peces")){
                try {
                    tipo = "Peces";
                    peso = an.CalcularPesoProm(2);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Reptiles")){
                try {
                    tipo = "Reptiles";
                    peso = an.CalcularPesoProm(3);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Aves")){
                try {
                    tipo = "Aves";
                    peso = an.CalcularPesoProm(4);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Anfibios")){
                try {
                    tipo ="Anfibios";
                    peso = an.CalcularPesoProm(5);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Artrópodos")){
                try {
                    tipo ="Artrópodos";
                    peso = an.CalcularPesoProm(6);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Moluscos")){
                try {
                    tipo ="Moluscos";
                    peso = an.CalcularPesoProm(7);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Equinodermos")){
                try {
                    tipo = "Equinodermos";
                    peso = an.CalcularPesoProm(8);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Gusanos")){
                try {
                    tipo = "Gusanos";
                    peso = an.CalcularPesoProm(9);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Poríferos")){
                try {
                    tipo = "Poríferos";
                    peso = an.CalcularPesoProm(10);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            if(recibido.equals("Celentéreos")){
                try {
                    tipo = "Celentéreos";
                    peso = an.CalcularPesoProm(11);
                } catch (SQLException ex) {
                    Logger.getLogger(Prom_TOG.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            DecimalFormat formato = new DecimalFormat("#.###");
            String numeroRedondeado = formato.format(peso);
            jTextArea1.setText("El promedio peso de "+ tipo +" es de: ");
            jTextField1.setText(""+numeroRedondeado);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        //Aqui estan las acciones del boton limpiar donde se dejan los textos con una cadena vacia
        jTextArea1.setText("");
        AquiReciboElTipoOGrupo.setText("");
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Esta es la accion del boton volver hacemos la nueva instancia del Menu y luego le decimos que se haga visible para acto despues usar this.dispose() para cerrar la ventana actual.
        Menu volver = new Menu();
        volver.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Prom_TOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Prom_TOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Prom_TOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Prom_TOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Prom_TOG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AquiReciboElTipoOGrupo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
